[package]
name = "align"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mfcc = {version="0.1.0", path="../mfcc"}
once_cell = "1.13.0"
symphonia = "0.5.0"
ndarray-csv = "0.5.1"
csv = "1.1.6"
